import React, { useState } from 'react';
import { FileCode, Copy, Check, X, PlayCircle, ShieldCheck, Download } from 'lucide-react';
import { AnalysisResult } from '../types';

interface UnitTestGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysisResult: AnalysisResult | null;
  code: string;
  language: string;
}

export const UnitTestGeneratorModal: React.FC<UnitTestGeneratorModalProps> = ({
  isOpen,
  onClose,
  analysisResult,
  code,
  language,
}) => {
  const [copied, setCopied] = useState(false);
  const [testFramework, setTestFramework] = useState<string>(
    language === 'python' ? 'pytest' : language === 'go' ? 'go-test' : 'vitest'
  );

  if (!isOpen) return null;

  // Generate test boilerplate based on analysis steps and symbols
  const generateUnitTestCode = () => {
    const steps = analysisResult?.steps || [];
    const symbols = analysisResult?.decodedSymbolsTable || [];
    const summary = analysisResult?.scriptSummary || 'Script logic verification';

    if (testFramework === 'pytest') {
      return `# -*- coding: utf-8 -*-
# Automated Unit Test generated by CodeFlow Decompiler & Visualizer
# Target: Python Script Verification
import pytest

def test_script_execution_flow():
    """
    Test Suite for: ${summary}
    Verifies state transformations across ${steps.length} execution steps.
    """
    print("[TEST] Starting automated simulation test...")
    
    # Assertions based on decoded symbols & step states
    ${symbols.length > 0 ? symbols.map(s => `# Symbol check: ${s.obfuscatedName} -> ${s.deobfuscatedMeaning}`).join('\n    ') : '    assert True'}
    
    # Execution steps verification
    steps_count = ${steps.length}
    assert steps_count > 0, "Execution steps must not be empty"
    print("[TEST] All assertions passed successfully!")

if __name__ == "__main__":
    pytest.main()
`;
    }

    if (testFramework === 'go-test') {
      return `package main

import (
	"testing"
)

// Automated Unit Test generated by CodeFlow Decompiler & Visualizer
func TestScriptLogic(t *testing.T) {
	// Summary: ${summary}
	t.Log("Initializing test suite for script verification...")

	stepsCount := ${steps.length}
	if stepsCount <= 0 {
		t.Fatalf("Expected execution steps > 0, got %d", stepsCount)
	}

	// Verify decoded symbols
	${symbols.length > 0 ? symbols.map(s => `t.Logf("Verified symbol: %s -> %s", "${s.obfuscatedName}", "${s.deobfuscatedMeaning}")`).join('\n\t') : '// No symbols to verify'}

	t.Log("Test completed successfully with 0 errors.")
}
`;
    }

    // Default Vitest / Jest for JS/TS
    return `import { describe, it, expect } from 'vitest';

/**
 * Automated Unit Test generated by CodeFlow Decompiler & Visualizer
 * Target Script Summary: ${summary}
 */
describe('CodeFlow Automated Script Test Suite', () => {
  it('should verify execution steps integrity', () => {
    const totalSteps = ${steps.length};
    expect(totalSteps).toBeGreaterThan(0);
  });

  it('should validate decoded obfuscated symbols and invariants', () => {
    const symbols = ${JSON.stringify(symbols, null, 2)};
    expect(Array.isArray(symbols)).toBe(true);
    
    // Ensure all symbols have deobfuscated meanings
    symbols.forEach((sym: any) => {
      expect(sym.deobfuscatedMeaning).toBeDefined();
    });
  });

  it('should pass sandbox simulation execution without throwing', () => {
    const runSimulationTest = () => {
      // Sandbox runtime check
      return true;
    };
    expect(runSimulationTest()).toBe(true);
  });
});
`;
  };

  const testCode = generateUnitTestCode();

  const handleCopy = () => {
    navigator.clipboard.writeText(testCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const handleDownload = () => {
    const ext = testFramework === 'pytest' ? 'py' : testFramework === 'go-test' ? 'go' : 'test.ts';
    const blob = new Blob([testCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `script.generated.${ext}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white border border-slate-200 rounded-2xl shadow-xl w-full max-w-3xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-5 py-4 bg-slate-900 text-white flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <PlayCircle className="w-5 h-5 text-emerald-400 animate-pulse" />
            <h3 className="font-bold text-base">ระบบสร้าง Unit Test อัตโนมัติ (Automated Unit Test Generator)</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-4 flex-1 overflow-auto max-h-[75vh] text-xs">
          <div className="flex flex-wrap items-center justify-between gap-3 p-3 bg-slate-50 border border-slate-200 rounded-xl">
            <div className="flex items-center gap-2">
              <span className="font-semibold text-slate-700">เลือกเฟรมเวิร์ก Unit Test:</span>
              <select
                value={testFramework}
                onChange={(e) => setTestFramework(e.target.value)}
                className="px-3 py-1.5 border border-slate-300 rounded-lg bg-white font-medium text-slate-800 focus:outline-hidden focus:ring-2 focus:ring-slate-900"
              >
                <option value="vitest">Vitest / Jest (JavaScript / TypeScript)</option>
                <option value="pytest">Pytest (Python)</option>
                <option value="go-test">Go Testing Package (Go)</option>
              </select>
            </div>
            <span className="text-slate-500 font-mono text-[11px]">
              สเต็ปวิเคราะห์ทั้งหมด: {analysisResult?.steps.length || 0} ขั้นตอน
            </span>
          </div>

          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="font-bold text-slate-800 flex items-center gap-1.5">
                <FileCode className="w-4 h-4 text-emerald-600" />
                โค้ด Unit Test ที่สร้างขึ้นโดยอัตโนมัติ (Boilerplate Test Code):
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopy}
                  className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-800 font-medium rounded-lg transition-colors flex items-center gap-1"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'คัดลอกแล้ว' : 'คัดลอกโค้ด'}
                </button>
                <button
                  type="button"
                  onClick={handleDownload}
                  className="px-3 py-1.5 bg-slate-900 hover:bg-slate-800 text-white font-medium rounded-lg transition-colors flex items-center gap-1"
                >
                  <Download className="w-3.5 h-3.5" />
                  ดาวน์โหลดไฟล์เทสต์
                </button>
              </div>
            </div>

            <pre className="p-4 bg-slate-950 text-emerald-400 font-mono text-xs rounded-xl overflow-x-auto max-h-96 border border-slate-800 leading-relaxed">
              {testCode}
            </pre>
          </div>

          <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl text-emerald-900 flex items-start gap-3">
            <ShieldCheck className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
            <div>
              <span className="font-bold text-sm block">คำแนะนำการตรวจสอบก่อน Deploy:</span>
              <p className="text-emerald-700 mt-0.5">
                คุณสามารถคัดลอกโค้ด Unit Test นี้ไปรันในเครื่องมือทดสอบประจำโปรเจกต์ของคุณ เพื่อยืนยันความถูกต้องของลอจิก (Logic Verification) และตรวจสอบความปลอดภัยก่อนนำไปใช้งานจริง
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 bg-slate-50 border-t border-slate-200 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-200 hover:bg-slate-300 text-slate-800 font-semibold rounded-xl transition-colors"
          >
            ปิดหน้าต่าง
          </button>
        </div>
      </div>
    </div>
  );
};
